version = 5.2.2
archive_dir = /etc/letsencrypt/archive/adribell.com
cert = /etc/letsencrypt/live/adribell.com/cert.pem
privkey = /etc/letsencrypt/live/adribell.com/privkey.pem
chain = /etc/letsencrypt/live/adribell.com/chain.pem
fullchain = /etc/letsencrypt/live/adribell.com/fullchain.pem
[renewalparams]
account = 1155c18902096a24783cae6e372d3039
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
adribell.com = /var/www/certbot
www.adribell.com = /var/www/certbot
